version: "3.8"
services:
  backend:
    image: ghcr.io/rhehfl/ai_talk:latest
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    networks:
      - ai_talk_net
    volumes:
      - ./config/personas.json:/usr/src/app/packages/back/dist/prompt/personas.json:ro

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - ai_talk_net

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    depends_on:
      - backend
    networks:
      - ai_talk_net

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot

volumes:
  redis-data:

networks:
  ai_talk_net:
